### PR TITLE
Phg/run bb e2e py

### PR DESCRIPTION
**Pull request by Pgarrett**
- Adding support for python e2e tests in spring-rest-bb and spring-graphql-bb.
- Minor fix in adding the content-type for rest requests

### CODE REVIEW

**Comment by arcuri82** [comment]
@Pgarrett thx ;) it looks like there is some issue with GitHub, that is not running the jobs :(  i ll merge once all green (i ll try to re-run the jobs). at the moment, unclear if issue is temporary at github, or something we introduced

**Comment by arcuri82** [comment]
@Pgarrett looks like there are some issues when running on Windows (eg my machine). i m looking into them now

**Comment by Pgarrett** [comment]
Hmm, I guess it'll be related to how to call `python`. I had looked into it and found that it was called the same way

**Comment by arcuri82** [comment]
@Pgarrett i saw at least 2 issues, which hopefully should be fixed now:
1) write-rights  (used `--user`, hopefully it does not have side effects)
2) timeouts don't work on Windows :( so they are disabled there now

**Comment by arcuri82** [comment]
in another branch, i should see to make sure that bb tests are run on Windows (and Mac) as well.
by default we don't run tests there, as those OS on GitHub have issues with Docker (at least last time i tried)

**Comment by Pgarrett** [comment]
Windows docker images require them to be executed in a Windows host, so yep, that won't run in CI. Surprised by the fact that timeouts don't work in Windows, I'll dig into it (I don't have a Windows PC but I'll see what I can find)

**Comment by Pgarrett** [comment]
@arcuri82 I've been looking at the test results and it seems changes in [this](https://github.com/WebFuzzing/EvoMaster/commit/8c6cbb8d6610b81e4f842b45db3d215b83b744f0) commit have broken the python implementation.
The test written is now something like:

```
requests \
    .post(self.baseUrlOfSut + "/api/logintoken/login")
    headers = {}
    headers["content-type"] = "application/json"
    body = " { " + \
        " \"username\": \"foo\", " + \
        " \"password\": \"123\" " + \
        " } "
    cookies_foo = requests \, 
                headers=headers, data=body.cookies
```

Which will naturally break since there's indentation issues and misplaced calls. It should be something like:
```
headers = {}
headers["content-type"] = "application/json"
body = " { " + \
    " \"username\": \"foo\", " + \
    " \"password\": \"123\" " + \
    " } "
cookies_foo = requests \
    .post(self.baseUrlOfSut + "/api/logintoken/login", 
        headers=headers, data=body).cookies
```
So as to be in sync, do you want me to fix it? It goes beyond OS issues, it's python writing, so I feel I should fix it. Just let me know and I'll tackle it!

**Comment by arcuri82** [comment]
@Pgarrett  yes, please fix it, as it is related to python writing

**Review by arcuri82 — CHANGES_REQUESTED** [review]
see failing E2E

**Comment by Pgarrett** [comment]
Fixed! @arcuri82

**Review by arcuri82 — APPROVED** [review]

**Pull request merged**
