### PR TITLE
Security 403 vs 404

### PR DESCRIPTION
**Pull request by arcuri82**

### CODE REVIEW

**Comment by arcuri82** [comment]
hi @man-zhang,
 can you have a look at the failing test `PCEMTest`?
It fails due to a new check added to `Individual.verifyValidity()`, where we verify that all local ids are indeed unique.
somehow, the mutator operator is breaking this.
do you have sometime for this?

**Comment by man-zhang** [comment]
hi, @arcuri82  I will have some time to check it tomorrow night.

**Comment by man-zhang** [comment]
hi @arcuri82  `PCEMTest` is fixed now.

**Comment by arcuri82** [comment]
@man-zhang thx!

**Comment by arcuri82** [comment]
@onurd86 you can have a look at the changes done in this PR

**Comment by onurd86** [comment]
@arcuri82 Sure I will take a look.

**Pull request merged**
